// THIS FILE IS AUTO-GENERATED, DONOT EDIT!!!

#ifndef VERSION_H
#define VERSION_H

#define APP_VERSION_MAJOR 2
#define APP_VERSION_MINOR 0
#define APP_VERSION_PATCH 1

#define STR_HELPER(x) #x
#define STR(x) STR_HELPER(x)

#define APP_VERSION_STRING STR(APP_VERSION_MAJOR) "." STR(APP_VERSION_MINOR) "." STR(APP_VERSION_PATCH)

#endif // VERSION_H
